from PyQt5.QtWidgets import QPushButton, QFrame, QGridLayout, QGraphicsDropShadowEffect
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QSize, Qt


class KeyboardWidget(QFrame):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        keyboard_layout = QGridLayout()

        self.esc_key = QPushButton('Esc')
        keyboard_layout.addWidget(self.esc_key, 1, 1, 1, 2)
        shadow1 = QGraphicsDropShadowEffect()
        shadow1.setBlurRadius(20)
        shadow1.setColor(Qt.darkCyan)
        shadow1.setOffset(4, 4)
        self.esc_key.setGraphicsEffect(shadow1)

        self.one_key = QPushButton('1')
        keyboard_layout.addWidget(self.one_key, 1, 3, 1, 2)
        shadow2 = QGraphicsDropShadowEffect()
        shadow2.setBlurRadius(20)
        shadow2.setColor(Qt.darkCyan)
        shadow2.setOffset(4, 4)
        self.one_key.setGraphicsEffect(shadow2)

        self.two_key = QPushButton('2')
        keyboard_layout.addWidget(self.two_key, 1, 5, 1, 2)
        shadow3 = QGraphicsDropShadowEffect()
        shadow3.setBlurRadius(20)
        shadow3.setColor(Qt.darkCyan)
        shadow3.setOffset(4, 4)
        self.two_key.setGraphicsEffect(shadow3)

        self.three_key = QPushButton('3')
        keyboard_layout.addWidget(self.three_key, 1, 7, 1, 2)
        shadow4 = QGraphicsDropShadowEffect()
        shadow4.setBlurRadius(20)
        shadow4.setColor(Qt.darkCyan)
        shadow4.setOffset(4, 4)
        self.three_key.setGraphicsEffect(shadow4)

        self.four_key = QPushButton('4')
        keyboard_layout.addWidget(self.four_key, 1, 9, 1, 2)
        shadow5 = QGraphicsDropShadowEffect()
        shadow5.setBlurRadius(20)
        shadow5.setColor(Qt.darkCyan)
        shadow5.setOffset(4, 4)
        self.four_key.setGraphicsEffect(shadow5)

        self.five_key = QPushButton('5')
        keyboard_layout.addWidget(self.five_key, 1, 11, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        self.six_key = QPushButton('6')
        keyboard_layout.addWidget(self.six_key, 1, 13, 1, 2)
        shadow7 = QGraphicsDropShadowEffect()
        shadow7.setBlurRadius(20)
        shadow7.setColor(Qt.darkCyan)
        shadow7.setOffset(4, 4)
        self.six_key.setGraphicsEffect(shadow7)

        self.seven_key = QPushButton('7')
        keyboard_layout.addWidget(self.seven_key, 1, 15, 1, 2)
        shadow8 = QGraphicsDropShadowEffect()
        shadow8.setBlurRadius(20)
        shadow8.setColor(Qt.darkCyan)
        shadow8.setOffset(4, 4)
        self.seven_key.setGraphicsEffect(shadow8)

        self.eight_key = QPushButton('8')
        keyboard_layout.addWidget(self.eight_key, 1, 17, 1, 2)
        shadow9 = QGraphicsDropShadowEffect()
        shadow9.setBlurRadius(20)
        shadow9.setColor(Qt.darkCyan)
        shadow9.setOffset(4, 4)
        self.eight_key.setGraphicsEffect(shadow9)

        self.nine_key = QPushButton('9')
        keyboard_layout.addWidget(self.nine_key, 1, 19, 1, 2)
        shadow10 = QGraphicsDropShadowEffect()
        shadow10.setBlurRadius(20)
        shadow10.setColor(Qt.darkCyan)
        shadow10.setOffset(4, 4)
        self.nine_key.setGraphicsEffect(shadow10)

        self.zero_key = QPushButton('0')
        keyboard_layout.addWidget(self.zero_key, 1, 21, 1, 2)
        shadow11 = QGraphicsDropShadowEffect()
        shadow11.setBlurRadius(20)
        shadow11.setColor(Qt.darkCyan)
        shadow11.setOffset(4, 4)
        self.zero_key.setGraphicsEffect(shadow11)

        self.minus_key = QPushButton('-')
        keyboard_layout.addWidget(self.minus_key, 1, 23, 1, 2)
        shadow12 = QGraphicsDropShadowEffect()
        shadow12.setBlurRadius(20)
        shadow12.setColor(Qt.darkCyan)
        shadow12.setOffset(4, 4)
        self.minus_key.setGraphicsEffect(shadow12)

        self.equal_key = QPushButton('=')
        keyboard_layout.addWidget(self.equal_key, 1, 25, 1, 2)
        shadow13 = QGraphicsDropShadowEffect()
        shadow13.setBlurRadius(20)
        shadow13.setColor(Qt.darkCyan)
        shadow13.setOffset(4, 4)
        self.equal_key.setGraphicsEffect(shadow13)

        self.backspace = QPushButton()
        keyboard_layout.addWidget(self.backspace, 1, 27, 1, 4)
        self.backspace.setIcon(QIcon('resources/icons8-clear-symbol-96.png'))
        self.backspace.setIconSize(QSize(24, 24))
        shadow14 = QGraphicsDropShadowEffect()
        shadow14.setBlurRadius(20)
        shadow14.setColor(Qt.darkCyan)
        shadow14.setOffset(4, 4)
        self.backspace.setGraphicsEffect(shadow14)

        self.tab_key = QPushButton('Tab')
        keyboard_layout.addWidget(self.tab_key, 2, 1, 1, 3)
        shadow15 = QGraphicsDropShadowEffect()
        shadow15.setBlurRadius(20)
        shadow15.setColor(Qt.darkCyan)
        shadow15.setOffset(4, 4)
        self.tab_key.setGraphicsEffect(shadow15)

        self.q_key = QPushButton('Q')
        keyboard_layout.addWidget(self.q_key, 2, 4, 1, 2)
        shadow16 = QGraphicsDropShadowEffect()
        shadow16.setBlurRadius(20)
        shadow16.setColor(Qt.darkCyan)
        shadow16.setOffset(4, 4)
        self.q_key.setGraphicsEffect(shadow16)

        self.w_key = QPushButton('W')
        keyboard_layout.addWidget(self.w_key, 2, 6, 1, 2)
        shadow17 = QGraphicsDropShadowEffect()
        shadow17.setBlurRadius(20)
        shadow17.setColor(Qt.darkCyan)
        shadow17.setOffset(4, 4)
        self.w_key.setGraphicsEffect(shadow17)

        self.e_key = QPushButton('E')
        keyboard_layout.addWidget(self.e_key, 2, 8, 1, 2)
        shadow18 = QGraphicsDropShadowEffect()
        shadow18.setBlurRadius(20)
        shadow18.setColor(Qt.darkCyan)
        shadow18.setOffset(4, 4)
        self.e_key.setGraphicsEffect(shadow18)

        self.r_key = QPushButton('R')
        keyboard_layout.addWidget(self.r_key, 2, 10, 1, 2)
        shadow19 = QGraphicsDropShadowEffect()
        shadow19.setBlurRadius(20)
        shadow19.setColor(Qt.darkCyan)
        shadow19.setOffset(4, 4)
        self.r_key.setGraphicsEffect(shadow19)

        self.t_key = QPushButton('T')
        keyboard_layout.addWidget(self.t_key, 2, 12, 1, 2)
        shadow20 = QGraphicsDropShadowEffect()
        shadow20.setBlurRadius(20)
        shadow20.setColor(Qt.darkCyan)
        shadow20.setOffset(4, 4)
        self.t_key.setGraphicsEffect(shadow20)

        self.y_key = QPushButton('Y')
        keyboard_layout.addWidget(self.y_key, 2, 14, 1, 2)
        shadow21 = QGraphicsDropShadowEffect()
        shadow21.setBlurRadius(20)
        shadow21.setColor(Qt.darkCyan)
        shadow21.setOffset(4, 4)
        self.y_key.setGraphicsEffect(shadow21)

        self.u_key = QPushButton('U')
        keyboard_layout.addWidget(self.u_key, 2, 16, 1, 2)
        shadow22 = QGraphicsDropShadowEffect()
        shadow22.setBlurRadius(20)
        shadow22.setColor(Qt.darkCyan)
        shadow22.setOffset(4, 4)
        self.u_key.setGraphicsEffect(shadow22)

        keyboard_layout.addWidget(QPushButton('I'), 2, 18, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('O'), 2, 20, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('P'), 2, 22, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('['), 2, 24, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton(']'), 2, 26, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('\\'), 2, 28, 1, 3)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('CapsLk'), 3, 1, 1, 4)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('A'), 3, 5, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('S'), 3, 7, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('D'), 3, 9, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('F'), 3, 11, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('G'), 3, 13, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('H'), 3, 15, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('J'), 3, 17, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('K'), 3, 19, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('L'), 3, 21, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton(';'), 3, 23, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('\''), 3, 25, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('Enter'), 3, 27, 1, 4)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('Shift'), 4, 1, 1, 5)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('Z'), 4, 6, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('X'), 4, 8, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('C'), 4, 10, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('V'), 4, 12, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('B'), 4, 14, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('N'), 4, 16, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('M'), 4, 18, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton(','), 4, 20, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('.'), 4, 22, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('/'), 4, 24, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('Shift'), 4, 26, 1, 5)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('Ctrl'), 5, 1, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        self.win_right_key = QPushButton()
        keyboard_layout.addWidget(self.win_right_key, 5, 3, 1, 2)
        self.win_right_key.setIcon(QIcon('resources/icons8-windows-10-96.png'))
        self.win_right_key.setIconSize(QSize(24, 24))
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('Alt'), 5, 5, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton(), 5, 7, 1, 16)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('Alt'), 5, 23, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        self.wind_left_key = QPushButton()
        keyboard_layout.addWidget(self.wind_left_key, 5, 25, 1, 2)
        self.wind_left_key.setIcon(QIcon('resources/icons8-windows-10-96.png'))
        self.wind_left_key.setIconSize(QSize(24, 24))
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        self.menu_key = QPushButton()
        keyboard_layout.addWidget(self.menu_key, 5, 27, 1, 2)
        self.menu_key.setIcon(QIcon('resources/icons8-menu-squared-96.png'))
        self.menu_key.setIconSize(QSize(24, 24))
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        keyboard_layout.addWidget(QPushButton('Ctrl'), 5, 29, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        self.setLayout(keyboard_layout)