from PyQt5.QtWidgets import QPushButton, QFrame, QGridLayout, QGraphicsDropShadowEffect
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QSize, Qt


class KeyboardWidget(QFrame):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        keyboard_layout = QGridLayout()

        self.esc_key = QPushButton('Esc')
        keyboard_layout.addWidget(self.esc_key, 1, 1, 1, 2)
        shadow1 = QGraphicsDropShadowEffect()
        shadow1.setBlurRadius(20)
        shadow1.setColor(Qt.darkCyan)
        shadow1.setOffset(4, 4)
        self.esc_key.setGraphicsEffect(shadow1)

        self.one_key = QPushButton('1')
        keyboard_layout.addWidget(self.one_key, 1, 3, 1, 2)
        shadow2 = QGraphicsDropShadowEffect()
        shadow2.setBlurRadius(20)
        shadow2.setColor(Qt.darkCyan)
        shadow2.setOffset(4, 4)
        self.one_key.setGraphicsEffect(shadow2)

        self.two_key = QPushButton('2')
        keyboard_layout.addWidget(self.two_key, 1, 5, 1, 2)
        shadow3 = QGraphicsDropShadowEffect()
        shadow3.setBlurRadius(20)
        shadow3.setColor(Qt.darkCyan)
        shadow3.setOffset(4, 4)
        self.two_key.setGraphicsEffect(shadow3)

        self.three_key = QPushButton('3')
        keyboard_layout.addWidget(self.three_key, 1, 7, 1, 2)
        shadow4 = QGraphicsDropShadowEffect()
        shadow4.setBlurRadius(20)
        shadow4.setColor(Qt.darkCyan)
        shadow4.setOffset(4, 4)
        self.three_key.setGraphicsEffect(shadow4)

        self.four_key = QPushButton('4')
        keyboard_layout.addWidget(self.four_key, 1, 9, 1, 2)
        shadow5 = QGraphicsDropShadowEffect()
        shadow5.setBlurRadius(20)
        shadow5.setColor(Qt.darkCyan)
        shadow5.setOffset(4, 4)
        self.four_key.setGraphicsEffect(shadow5)

        self.five_key = QPushButton('5')
        keyboard_layout.addWidget(self.five_key, 1, 11, 1, 2)
        shadow6 = QGraphicsDropShadowEffect()
        shadow6.setBlurRadius(20)
        shadow6.setColor(Qt.darkCyan)
        shadow6.setOffset(4, 4)
        self.five_key.setGraphicsEffect(shadow6)

        self.six_key = QPushButton('6')
        keyboard_layout.addWidget(self.six_key, 1, 13, 1, 2)
        shadow7 = QGraphicsDropShadowEffect()
        shadow7.setBlurRadius(20)
        shadow7.setColor(Qt.darkCyan)
        shadow7.setOffset(4, 4)
        self.six_key.setGraphicsEffect(shadow7)

        self.seven_key = QPushButton('7')
        keyboard_layout.addWidget(self.seven_key, 1, 15, 1, 2)
        shadow8 = QGraphicsDropShadowEffect()
        shadow8.setBlurRadius(20)
        shadow8.setColor(Qt.darkCyan)
        shadow8.setOffset(4, 4)
        self.seven_key.setGraphicsEffect(shadow8)

        self.eight_key = QPushButton('8')
        keyboard_layout.addWidget(self.eight_key, 1, 17, 1, 2)
        shadow9 = QGraphicsDropShadowEffect()
        shadow9.setBlurRadius(20)
        shadow9.setColor(Qt.darkCyan)
        shadow9.setOffset(4, 4)
        self.eight_key.setGraphicsEffect(shadow9)

        self.nine_key = QPushButton('9')
        keyboard_layout.addWidget(self.nine_key, 1, 19, 1, 2)
        shadow10 = QGraphicsDropShadowEffect()
        shadow10.setBlurRadius(20)
        shadow10.setColor(Qt.darkCyan)
        shadow10.setOffset(4, 4)
        self.nine_key.setGraphicsEffect(shadow10)

        self.zero_key = QPushButton('0')
        keyboard_layout.addWidget(self.zero_key, 1, 21, 1, 2)
        shadow11 = QGraphicsDropShadowEffect()
        shadow11.setBlurRadius(20)
        shadow11.setColor(Qt.darkCyan)
        shadow11.setOffset(4, 4)
        self.zero_key.setGraphicsEffect(shadow11)

        self.minus_key = QPushButton('-')
        keyboard_layout.addWidget(self.minus_key, 1, 23, 1, 2)
        shadow12 = QGraphicsDropShadowEffect()
        shadow12.setBlurRadius(20)
        shadow12.setColor(Qt.darkCyan)
        shadow12.setOffset(4, 4)
        self.minus_key.setGraphicsEffect(shadow12)

        self.equal_key = QPushButton('=')
        keyboard_layout.addWidget(self.equal_key, 1, 25, 1, 2)
        shadow13 = QGraphicsDropShadowEffect()
        shadow13.setBlurRadius(20)
        shadow13.setColor(Qt.darkCyan)
        shadow13.setOffset(4, 4)
        self.equal_key.setGraphicsEffect(shadow13)

        self.backspace = QPushButton()
        keyboard_layout.addWidget(self.backspace, 1, 27, 1, 4)
        self.backspace.setIcon(QIcon('resources/icons8-clear-symbol-96.png'))
        self.backspace.setIconSize(QSize(24, 24))
        shadow14 = QGraphicsDropShadowEffect()
        shadow14.setBlurRadius(20)
        shadow14.setColor(Qt.darkCyan)
        shadow14.setOffset(4, 4)
        self.backspace.setGraphicsEffect(shadow14)

        self.tab_key = QPushButton('Tab')
        keyboard_layout.addWidget(self.tab_key, 2, 1, 1, 3)
        shadow15 = QGraphicsDropShadowEffect()
        shadow15.setBlurRadius(20)
        shadow15.setColor(Qt.darkCyan)
        shadow15.setOffset(4, 4)
        self.tab_key.setGraphicsEffect(shadow15)

        self.q_key = QPushButton('Q')
        keyboard_layout.addWidget(self.q_key, 2, 4, 1, 2)
        shadow16 = QGraphicsDropShadowEffect()
        shadow16.setBlurRadius(20)
        shadow16.setColor(Qt.darkCyan)
        shadow16.setOffset(4, 4)
        self.q_key.setGraphicsEffect(shadow16)

        self.w_key = QPushButton('W')
        keyboard_layout.addWidget(self.w_key, 2, 6, 1, 2)
        shadow17 = QGraphicsDropShadowEffect()
        shadow17.setBlurRadius(20)
        shadow17.setColor(Qt.darkCyan)
        shadow17.setOffset(4, 4)
        self.w_key.setGraphicsEffect(shadow17)

        self.e_key = QPushButton('E')
        keyboard_layout.addWidget(self.e_key, 2, 8, 1, 2)
        shadow18 = QGraphicsDropShadowEffect()
        shadow18.setBlurRadius(20)
        shadow18.setColor(Qt.darkCyan)
        shadow18.setOffset(4, 4)
        self.e_key.setGraphicsEffect(shadow18)

        self.r_key = QPushButton('R')
        keyboard_layout.addWidget(self.r_key, 2, 10, 1, 2)
        shadow19 = QGraphicsDropShadowEffect()
        shadow19.setBlurRadius(20)
        shadow19.setColor(Qt.darkCyan)
        shadow19.setOffset(4, 4)
        self.r_key.setGraphicsEffect(shadow19)

        self.t_key = QPushButton('T')
        keyboard_layout.addWidget(self.t_key, 2, 12, 1, 2)
        shadow20 = QGraphicsDropShadowEffect()
        shadow20.setBlurRadius(20)
        shadow20.setColor(Qt.darkCyan)
        shadow20.setOffset(4, 4)
        self.t_key.setGraphicsEffect(shadow20)

        self.y_key = QPushButton('Y')
        keyboard_layout.addWidget(self.y_key, 2, 14, 1, 2)
        shadow21 = QGraphicsDropShadowEffect()
        shadow21.setBlurRadius(20)
        shadow21.setColor(Qt.darkCyan)
        shadow21.setOffset(4, 4)
        self.y_key.setGraphicsEffect(shadow21)

        self.u_key = QPushButton('U')
        keyboard_layout.addWidget(self.u_key, 2, 16, 1, 2)
        shadow22 = QGraphicsDropShadowEffect()
        shadow22.setBlurRadius(20)
        shadow22.setColor(Qt.darkCyan)
        shadow22.setOffset(4, 4)
        self.u_key.setGraphicsEffect(shadow22)

        self.i_key = QPushButton('I')
        keyboard_layout.addWidget(self.i_key, 2, 18, 1, 2)
        shadow23 = QGraphicsDropShadowEffect()
        shadow23.setBlurRadius(20)
        shadow23.setColor(Qt.darkCyan)
        shadow23.setOffset(4, 4)
        self.i_key.setGraphicsEffect(shadow23)

        self.o_key = QPushButton('O')
        keyboard_layout.addWidget(self.o_key, 2, 20, 1, 2)
        shadow24 = QGraphicsDropShadowEffect()
        shadow24.setBlurRadius(20)
        shadow24.setColor(Qt.darkCyan)
        shadow24.setOffset(4, 4)
        self.o_key.setGraphicsEffect(shadow24)

        self.p_key = QPushButton('P')
        keyboard_layout.addWidget(self.p_key, 2, 22, 1, 2)
        shadow25 = QGraphicsDropShadowEffect()
        shadow25.setBlurRadius(20)
        shadow25.setColor(Qt.darkCyan)
        shadow25.setOffset(4, 4)
        self.p_key.setGraphicsEffect(shadow25)

        self.open_bracket_key = QPushButton('[')
        keyboard_layout.addWidget(self.open_bracket_key, 2, 24, 1, 2)
        shadow26 = QGraphicsDropShadowEffect()
        shadow26.setBlurRadius(20)
        shadow26.setColor(Qt.darkCyan)
        shadow26.setOffset(4, 4)
        self.open_bracket_key.setGraphicsEffect(shadow26)

        self.close_bracket_key = QPushButton(']')
        keyboard_layout.addWidget(self.close_bracket_key, 2, 26, 1, 2)
        shadow27 = QGraphicsDropShadowEffect()
        shadow27.setBlurRadius(20)
        shadow27.setColor(Qt.darkCyan)
        shadow27.setOffset(4, 4)
        self.close_bracket_key.setGraphicsEffect(shadow27)

        self.backslash_key = QPushButton('\\')
        keyboard_layout.addWidget(self.backslash_key, 2, 28, 1, 3)
        shadow28 = QGraphicsDropShadowEffect()
        shadow28.setBlurRadius(20)
        shadow28.setColor(Qt.darkCyan)
        shadow28.setOffset(4, 4)
        self.backslash_key.setGraphicsEffect(shadow28)

        self.capslk_key = QPushButton('CapsLk')
        keyboard_layout.addWidget(self.capslk_key, 3, 1, 1, 4)
        shadow29 = QGraphicsDropShadowEffect()
        shadow29.setBlurRadius(20)
        shadow29.setColor(Qt.darkCyan)
        shadow29.setOffset(4, 4)
        self.capslk_key.setGraphicsEffect(shadow29)

        self.a_key = QPushButton('A')
        keyboard_layout.addWidget(self.a_key, 3, 5, 1, 2)
        shadow30 = QGraphicsDropShadowEffect()
        shadow30.setBlurRadius(20)
        shadow30.setColor(Qt.darkCyan)
        shadow30.setOffset(4, 4)
        self.a_key.setGraphicsEffect(shadow30)

        self.s_key = QPushButton('S')
        keyboard_layout.addWidget(self.s_key, 3, 7, 1, 2)
        shadow31 = QGraphicsDropShadowEffect()
        shadow31.setBlurRadius(20)
        shadow31.setColor(Qt.darkCyan)
        shadow31.setOffset(4, 4)
        self.s_key.setGraphicsEffect(shadow31)

        self.d_key = QPushButton('D')
        keyboard_layout.addWidget(self.d_key, 3, 9, 1, 2)
        shadow32 = QGraphicsDropShadowEffect()
        shadow32.setBlurRadius(20)
        shadow32.setColor(Qt.darkCyan)
        shadow32.setOffset(4, 4)
        self.d_key.setGraphicsEffect(shadow32)

        self.f_key = QPushButton('F')
        keyboard_layout.addWidget(self.f_key, 3, 11, 1, 2)
        shadow33 = QGraphicsDropShadowEffect()
        shadow33.setBlurRadius(20)
        shadow33.setColor(Qt.darkCyan)
        shadow33.setOffset(4, 4)
        self.f_key.setGraphicsEffect(shadow33)

        self.g_key = QPushButton('G')
        keyboard_layout.addWidget(self.g_key, 3, 13, 1, 2)
        shadow34 = QGraphicsDropShadowEffect()
        shadow34.setBlurRadius(20)
        shadow34.setColor(Qt.darkCyan)
        shadow34.setOffset(4, 4)
        self.g_key.setGraphicsEffect(shadow34)

        self.h_key = QPushButton('H')
        keyboard_layout.addWidget(self.h_key, 3, 15, 1, 2)
        shadow35 = QGraphicsDropShadowEffect()
        shadow35.setBlurRadius(20)
        shadow35.setColor(Qt.darkCyan)
        shadow35.setOffset(4, 4)
        self.h_key.setGraphicsEffect(shadow35)

        self.j_key = QPushButton('J')
        keyboard_layout.addWidget(self.j_key, 3, 17, 1, 2)
        shadow36 = QGraphicsDropShadowEffect()
        shadow36.setBlurRadius(20)
        shadow36.setColor(Qt.darkCyan)
        shadow36.setOffset(4, 4)
        self.j_key.setGraphicsEffect(shadow36)

        self.k_key = QPushButton('K')
        keyboard_layout.addWidget(self.k_key, 3, 19, 1, 2)
        shadow37 = QGraphicsDropShadowEffect()
        shadow37.setBlurRadius(20)
        shadow37.setColor(Qt.darkCyan)
        shadow37.setOffset(4, 4)
        self.k_key.setGraphicsEffect(shadow37)

        self.l_key = QPushButton('L')
        keyboard_layout.addWidget(self.l_key, 3, 21, 1, 2)
        shadow38 = QGraphicsDropShadowEffect()
        shadow38.setBlurRadius(20)
        shadow38.setColor(Qt.darkCyan)
        shadow38.setOffset(4, 4)
        self.l_key.setGraphicsEffect(shadow38)

        self.semicolon_key = QPushButton(';')
        keyboard_layout.addWidget(self.semicolon_key, 3, 23, 1, 2)
        shadow39 = QGraphicsDropShadowEffect()
        shadow39.setBlurRadius(20)
        shadow39.setColor(Qt.darkCyan)
        shadow39.setOffset(4, 4)
        self.semicolon_key.setGraphicsEffect(shadow39)

        self.quote_key = QPushButton('\'')
        keyboard_layout.addWidget(self.quote_key, 3, 25, 1, 2)
        shadow40 = QGraphicsDropShadowEffect()
        shadow40.setBlurRadius(20)
        shadow40.setColor(Qt.darkCyan)
        shadow40.setOffset(4, 4)
        self.quote_key.setGraphicsEffect(shadow40)

        self.enter_key = QPushButton('Enter')
        keyboard_layout.addWidget(self.enter_key, 3, 27, 1, 4)
        shadow41 = QGraphicsDropShadowEffect()
        shadow41.setBlurRadius(20)
        shadow41.setColor(Qt.darkCyan)
        shadow41.setOffset(4, 4)
        self.enter_key.setGraphicsEffect(shadow41)

        self.left_shift_key = QPushButton('Shift')
        keyboard_layout.addWidget(self.left_shift_key, 4, 1, 1, 5)
        shadow42 = QGraphicsDropShadowEffect()
        shadow42.setBlurRadius(20)
        shadow42.setColor(Qt.darkCyan)
        shadow42.setOffset(4, 4)
        self.left_shift_key.setGraphicsEffect(shadow42)

        self.z_key = QPushButton('Z')
        keyboard_layout.addWidget(self.z_key, 4, 6, 1, 2)
        shadow43 = QGraphicsDropShadowEffect()
        shadow43.setBlurRadius(20)
        shadow43.setColor(Qt.darkCyan)
        shadow43.setOffset(4, 4)
        self.z_key.setGraphicsEffect(shadow43)

        self.x_key = QPushButton('X')
        keyboard_layout.addWidget(self.x_key, 4, 8, 1, 2)
        shadow44 = QGraphicsDropShadowEffect()
        shadow44.setBlurRadius(20)
        shadow44.setColor(Qt.darkCyan)
        shadow44.setOffset(4, 4)
        self.x_key.setGraphicsEffect(shadow44)

        self.c_key = QPushButton('C')
        keyboard_layout.addWidget(self.c_key, 4, 10, 1, 2)
        shadow45 = QGraphicsDropShadowEffect()
        shadow45.setBlurRadius(20)
        shadow45.setColor(Qt.darkCyan)
        shadow45.setOffset(4, 4)
        self.c_key.setGraphicsEffect(shadow45)

        self.v_key = QPushButton('V')
        keyboard_layout.addWidget(self.v_key, 4, 12, 1, 2)
        shadow46 = QGraphicsDropShadowEffect()
        shadow46.setBlurRadius(20)
        shadow46.setColor(Qt.darkCyan)
        shadow46.setOffset(4, 4)
        self.v_key.setGraphicsEffect(shadow46)

        self.b_key = QPushButton('B')
        keyboard_layout.addWidget(self.b_key, 4, 14, 1, 2)
        shadow47 = QGraphicsDropShadowEffect()
        shadow47.setBlurRadius(20)
        shadow47.setColor(Qt.darkCyan)
        shadow47.setOffset(4, 4)
        self.b_key.setGraphicsEffect(shadow47)

        self.n_key = QPushButton('N')
        keyboard_layout.addWidget(self.n_key, 4, 16, 1, 2)
        shadow48 = QGraphicsDropShadowEffect()
        shadow48.setBlurRadius(20)
        shadow48.setColor(Qt.darkCyan)
        shadow48.setOffset(4, 4)
        self.n_key.setGraphicsEffect(shadow48)

        self.m_key = QPushButton('M')
        keyboard_layout.addWidget(self.m_key, 4, 18, 1, 2)
        shadow49 = QGraphicsDropShadowEffect()
        shadow49.setBlurRadius(20)
        shadow49.setColor(Qt.darkCyan)
        shadow49.setOffset(4, 4)
        self.m_key.setGraphicsEffect(shadow49)

        self.comma_key = QPushButton(',')
        keyboard_layout.addWidget(self.comma_key, 4, 20, 1, 2)
        shadow50 = QGraphicsDropShadowEffect()
        shadow50.setBlurRadius(20)
        shadow50.setColor(Qt.darkCyan)
        shadow50.setOffset(4, 4)
        self.comma_key.setGraphicsEffect(shadow50)

        self.dot_key = QPushButton('.')
        keyboard_layout.addWidget(self.dot_key, 4, 22, 1, 2)
        shadow51 = QGraphicsDropShadowEffect()
        shadow51.setBlurRadius(20)
        shadow51.setColor(Qt.darkCyan)
        shadow51.setOffset(4, 4)
        self.dot_key.setGraphicsEffect(shadow51)

        self.slash_key = QPushButton('/')
        keyboard_layout.addWidget(self.slash_key, 4, 24, 1, 2)
        shadow52 = QGraphicsDropShadowEffect()
        shadow52.setBlurRadius(20)
        shadow52.setColor(Qt.darkCyan)
        shadow52.setOffset(4, 4)
        self.slash_key.setGraphicsEffect(shadow52)

        self.right_shift_key = QPushButton('Shift')
        keyboard_layout.addWidget(self.right_shift_key, 4, 26, 1, 5)
        shadow53 = QGraphicsDropShadowEffect()
        shadow53.setBlurRadius(20)
        shadow53.setColor(Qt.darkCyan)
        shadow53.setOffset(4, 4)
        self.right_shift_key.setGraphicsEffect(shadow53)

        self.left_ctrl_key = QPushButton('Ctrl')
        keyboard_layout.addWidget(self.left_ctrl_key, 5, 1, 1, 2)
        shadow54 = QGraphicsDropShadowEffect()
        shadow54.setBlurRadius(20)
        shadow54.setColor(Qt.darkCyan)
        shadow54.setOffset(4, 4)
        self.left_ctrl_key.setGraphicsEffect(shadow54)

        self.win_right_key = QPushButton()
        keyboard_layout.addWidget(self.win_right_key, 5, 3, 1, 2)
        self.win_right_key.setIcon(QIcon('resources/icons8-windows-10-96.png'))
        self.win_right_key.setIconSize(QSize(24, 24))
        shadow55 = QGraphicsDropShadowEffect()
        shadow55.setBlurRadius(20)
        shadow55.setColor(Qt.darkCyan)
        shadow55.setOffset(4, 4)
        self.win_right_key.setGraphicsEffect(shadow55)

        self.left_alt_key = QPushButton('Alt')
        keyboard_layout.addWidget(self.left_alt_key, 5, 5, 1, 2)
        shadow56 = QGraphicsDropShadowEffect()
        shadow56.setBlurRadius(20)
        shadow56.setColor(Qt.darkCyan)
        shadow56.setOffset(4, 4)
        self.left_alt_key.setGraphicsEffect(shadow56)

        self.space_key = QPushButton()
        keyboard_layout.addWidget(self.space_key, 5, 7, 1, 16)
        shadow57 = QGraphicsDropShadowEffect()
        shadow57.setBlurRadius(20)
        shadow57.setColor(Qt.darkCyan)
        shadow57.setOffset(4, 4)
        self.space_key.setGraphicsEffect(shadow57)

        self.right_alt_key = QPushButton('Alt')
        keyboard_layout.addWidget(self.right_alt_key, 5, 23, 1, 2)
        shadow58 = QGraphicsDropShadowEffect()
        shadow58.setBlurRadius(20)
        shadow58.setColor(Qt.darkCyan)
        shadow58.setOffset(4, 4)
        self.right_alt_key.setGraphicsEffect(shadow58)

        self.wind_left_key = QPushButton()
        keyboard_layout.addWidget(self.wind_left_key, 5, 25, 1, 2)
        self.wind_left_key.setIcon(QIcon('resources/icons8-windows-10-96.png'))
        self.wind_left_key.setIconSize(QSize(24, 24))
        shadow59 = QGraphicsDropShadowEffect()
        shadow59.setBlurRadius(20)
        shadow59.setColor(Qt.darkCyan)
        shadow59.setOffset(4, 4)
        self.wind_left_key.setGraphicsEffect(shadow59)

        self.menu_key = QPushButton()
        keyboard_layout.addWidget(self.menu_key, 5, 27, 1, 2)
        self.menu_key.setIcon(QIcon('resources/icons8-menu-squared-96.png'))
        self.menu_key.setIconSize(QSize(24, 24))
        shadow60 = QGraphicsDropShadowEffect()
        shadow60.setBlurRadius(20)
        shadow60.setColor(Qt.darkCyan)
        shadow60.setOffset(4, 4)
        self.menu_key.setGraphicsEffect(shadow60)

        self.right_ctrl_key = QPushButton('Ctrl')
        keyboard_layout.addWidget(self.right_ctrl_key, 5, 29, 1, 2)
        shadow61 = QGraphicsDropShadowEffect()
        shadow61.setBlurRadius(20)
        shadow61.setColor(Qt.darkCyan)
        shadow61.setOffset(4, 4)
        self.right_ctrl_key.setGraphicsEffect(shadow61)

        self.setLayout(keyboard_layout)